
services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot_webhook:app --host 0.0.0.0 --port 10000
    autoDeploy: true
