name: Deploy to Render

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Работает на последней версии Ubuntu

    steps:
      # Шаг 1: Проверяем код
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Указываем версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Проверка переменных окружения для деплоя
      - name: Check RENDER_SERVICE_ID variable
        run: echo "Render Service ID: ${{ secrets.RENDER_SERVICE_ID }}"

      # Шаг 5: Запускаем деплой на Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            https://api.render.com/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}'
