name: Deploy to Render

on:
  push:
    branches:
      - main  # Триггер для главной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up environment variables
      - name: Set up environment variables
        run: echo "RENDER_SERVICE_ID=${{ secrets.RENDER_SERVICE_ID }}" >> $GITHUB_ENV

      # Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"service_id": "$RENDER_SERVICE_ID"}'

